import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'english' | 'hindi';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  english: {
    // Navigation
    'nav.home': 'Home',
    'nav.mood': 'Mood Tracker',
    'nav.ai': 'AI Support',
    'nav.booking': 'Book Session',
    // 'nav.resources' removed (merged into activities)
    'nav.community': 'Community',
    'nav.pomodoro': 'Pomodoro',
    'nav.journal': 'Journal',
    'nav.activities': 'Resources & Activities',
    'nav.local': 'Local Support',
    'nav.assessment': 'Assessment',
    'nav.admin': 'Admin Dashboard',
    'nav.donation': 'Donation',
    'nav.about': 'About Us',
    'nav.profile': 'My Profile',
    'nav.signin': 'Sign In',
    
    // Common
    'common.english': 'English',
    'common.hindi': 'हिंदी',
    'common.navigation': 'Navigation',
    'common.subscribe': 'Subscribe',
    'common.email.placeholder': 'Enter your email',
    'common.unsubscribe': 'Unsubscribe anytime',
    'common.wellness.tips': 'Get wellness tips and platform updates',
    'common.search': 'Search',
    'common.clear': 'Clear',
    'common.start': 'Start',
    'common.continue': 'Continue',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Footer
    'footer.brand': 'Maitri',
    'footer.brand.tagline': 'Empowering mental wellness through technology, community, and compassionate care. Your journey to better mental health starts here.',
    'footer.newsletter.title': 'Stay Updated',
    'footer.platform': 'Platform',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.crisis.support': 'Crisis Support',
    'footer.crisis.text': 'If you\'re having thoughts of self-harm, call our crisis line: 1800-599-0019',
    'footer.copyright': '© 2025 Maitri. All rights reserved. | Made with ❤️ for astronaut mental health',
    
    // Footer Links
    'footer.link.about': 'About Us',
    'footer.link.resources': 'Resources',
    'footer.link.community': 'Community',
    'footer.link.ai': 'AI Support',
    'footer.link.crisis': 'Crisis Helpline',
    'footer.link.booking': 'Book Session',
    'footer.link.local': 'Local Support',
    'footer.link.emergency': 'Emergency Resources',
    'footer.link.privacy': 'Privacy Policy',
    'footer.link.terms': 'Terms of Service',
    'footer.link.cookies': 'Cookie Policy',
    'footer.link.accessibility': 'Accessibility',
    
    // Contact Info
    'contact.email': 'hello@maitri.space',
    'contact.phone': '1800-599-0019',
    'contact.location': 'Pune, India',
    
    // Dashboard/Homepage
    'dashboard.hero.title': 'Your Mental Health Matters Most',
    'dashboard.hero.subtitle': 'A comprehensive digital mental health platform designed for astronauts and space explorers. Mission-focused, privacy-first, and always accessible—even when communication with Earth is impossible.',
    'dashboard.hero.cta': 'Start Your Wellness Journey',
    'dashboard.hero.emergency': 'Emergency Support',
    'dashboard.daily.inspiration': 'Daily Inspiration',
    'dashboard.daily.subtitle': 'Strength and wisdom for your journey',
    'dashboard.challenges.title': 'Common Challenges We Address',
    'dashboard.challenges.subtitle': 'Support for students navigating common mental health challenges',
    'dashboard.differentiators.title': 'Why Maitri Stands Out',
    'dashboard.differentiators.subtitle': 'Built specifically for astronauts and space explorers with unique features that address the real challenges of long-duration space missions',
    'dashboard.features.title': 'Comprehensive Mental Health Support',
    'dashboard.features.subtitle': 'Everything you need for mental wellness, from AI support to peer connections',
    'dashboard.cta.title': 'Ready to Prioritize Your Mental Health?',
    'dashboard.cta.subtitle': 'Join thousands of astronauts who are taking control of their mental wellness with Maitri',
    'dashboard.cta.get_started': 'Get Started Today',
    'dashboard.cta.learn_more': 'Learn More',
    
    // Features
    'feature.ai.title': 'TARS AI Mental Health Support',
    'feature.ai.description': '24/7 TARS AI companion providing immediate coping strategies, crisis intervention, and psychological support—even when communication with Earth is impossible.',
    'feature.ai.action': 'Start Chat',
    'feature.mood.title': 'Mission Mood Tracking & Analytics',
    'feature.mood.description': 'Private mood monitoring with weekly insights and mission-focused analytics for better psychological well-being awareness during space missions.',
    'feature.mood.action': 'Track Mood',
    'feature.counselling.title': 'Psychological Support Sessions',
    'feature.counselling.description': 'Secure booking system for space psychology professionals and mental health specialists with complete privacy protection for astronauts.',
    'feature.counselling.action': 'Book Session',
    'feature.resources.title': 'Mission Wellness Resources Hub',
    'feature.resources.description': 'Curated mental health content for space missions including meditation guides, relaxation audio for microgravity, and mission-focused educational materials.',
    'feature.resources.action': 'Explore Resources',
    'feature.community.title': 'Astronaut Support Community',
    'feature.community.description': 'Moderated astronaut-to-astronaut support forums with experienced space explorers providing safe, judgment-free guidance for mission challenges.',
    'feature.community.action': 'Join Community',
    'feature.pomodoro.title': 'Mission Focus Coach',
    'feature.pomodoro.description': 'Integrated mission task timer with mindfulness breaks, wellness streaks, and productivity insights for balanced space operations and psychological well-being.',
    'feature.pomodoro.action': 'Start Session',
    
    // AI Chat
    'ai.title': 'Maitri AI Companion',
    'ai.subtitle': '24/7 Mission Support • TARS AI • Astronaut-Focused',
    'ai.emergency.title': 'In Crisis? Get Immediate Help:',
    'ai.emergency.text': 'Campus Emergency: 1800-599-0019 | KIRAN: 1800-599-0019 | Suicide Prevention: 9152987821',
    'ai.emergency.call': 'Call Now',
    'ai.mode.quick': 'Quick',
    'ai.mode.detailed': 'Detailed',
    'ai.placeholder': 'Type your message...',
    'ai.send': 'Send',
    'ai.welcome': 'Hello! I\'m TARS, your AI companion from Maitri. I understand the unique challenges faced by astronauts during long-duration space missions - from isolation to mission stress. I\'m here 24/7 to provide mission-focused support, coping strategies, and guidance. How are you feeling today?',
    
    // Activities
    'activities.title': 'Resources & Activities',
    'activities.description': 'Explore videos, audio, articles, and guides curated for astronaut mental health during space missions, plus interactive activities to practice daily during long-duration missions.',
    'activities.available': 'Available Activities',
    'activities.available.desc': 'Diverse wellness options',
    'activities.completed': 'Completed Today',
    'activities.completed.desc': 'Keep building habits',
    'activities.categories': 'Activity Categories',
    'activities.categories.desc': 'Different wellness areas',
    'activities.streak': 'Weekly Streak',
    'activities.streak.desc': 'Days with activities',
    'activities.recommendations': 'Quick Recommendations',
    'activities.recommendations.desc': 'Based on common astronaut needs during space missions, here are some popular activities to try now:',
    'activities.search.placeholder': 'Search activities by name, benefits, or category...',
    'activities.no.found': 'No activities found',
    'activities.no.found.desc': 'Try adjusting your search criteria or exploring different categories to find activities that match your interests.',
    'activities.clear.filters': 'Clear filters',
    'activities.find.activity': 'Find Activity',
    'activities.tips.title': 'Activity Tips',
    'activities.time.suggestions': 'Time-Based Suggestions',
    
    // Resources (page removed)
    'resources.title': 'Resources',
    'resources.description': 'Curated mental health content.',
    'resources.search.placeholder': 'Search...',
    'resources.category.all': 'All Resources',
    'resources.category.articles': 'Articles & Guides',
    'resources.category.meditation': 'Meditation & Audio',
    'resources.category.crisis': 'Crisis Support',
    'resources.category.tools': 'Self-Help Tools',
    'resources.category.videos': 'Educational Videos',
    'resources.no.found': 'No resources found',
    'resources.no.found.desc': 'Try adjusting your search criteria or browse different categories.',
    
    // Floating Action Button
    'fab.ai.chat': 'AI Chat Support',
    'fab.emergency': 'Emergency Helpline',
    'fab.help': 'Get Help',
    
    // Mood Tracker
    'moodTracker.title': 'Mood Tracker',
    'moodTracker.subtitle': 'Track your emotional well-being and discover patterns',
    'moodTracker.dailyEntry': "Today's Mood",
    'moodTracker.dailyDescription': 'How are you feeling today?',
    'moodTracker.moods.great': 'Great',
    'moodTracker.moods.good': 'Good',
    'moodTracker.moods.okay': 'Okay',
    'moodTracker.moods.low': 'Low',
    'moodTracker.moods.struggling': 'Struggling',
    'moodTracker.whatsOnMind': "What's on your mind? (Optional)",
    'moodTracker.placeholder': 'Share your thoughts, feelings, or what happened today...',
    'moodTracker.recordMood': 'Record Mood',
    'moodTracker.recorded': 'Mood Recorded ✓',
    'moodTracker.weekOverview': 'Weekly Overview',
    'moodTracker.weekDescription': 'Your mood patterns over the past week',
    'moodTracker.averageMood': 'Average Mood',
    'moodTracker.progress': 'Your Progress',
    'moodTracker.daysTracked': 'Days Tracked',
    'moodTracker.wellnessStreak': 'Wellness Streak',
    'moodTracker.aboveAverage': 'Above Average',
    'moodTracker.insights': 'Mood Insights',
    'moodTracker.patternDetected': 'Pattern Detected',
    'moodTracker.patternMessage': 'Your mood tends to improve on weekends. Consider incorporating more relaxing activities during weekdays.',
    'moodTracker.positiveTrigger': 'Positive Trigger',
    'moodTracker.triggerMessage': 'Exercise and meditation appear to boost your mood significantly.',
    'moodTracker.viewResources': 'View Resources',
    'moodTracker.privacyNotice': 'Your mood data is private and secure. Only you can see your personal entries.',
    'moodTracker.days.mon': 'Mon',
    'moodTracker.days.tue': 'Tue',
    'moodTracker.days.wed': 'Wed',
    'moodTracker.days.thu': 'Thu',
    'moodTracker.days.fri': 'Fri',
    'moodTracker.days.sat': 'Sat',
    'moodTracker.days.sun': 'Sun',
    'moodTracker.activities.study': 'Study',
    'moodTracker.activities.exercise': 'Exercise',
    'moodTracker.activities.social': 'Social',
    'moodTracker.activities.rest': 'Rest',
    'moodTracker.activities.meditation': 'Meditation',
    'moodTracker.activities.exam': 'Exam',
    'moodTracker.activities.stress': 'Stress',
    'moodTracker.activities.friends': 'Friends',
    'moodTracker.activities.relax': 'Relax',
    'moodTracker.activities.family': 'Family',
    'moodTracker.activities.fun': 'Fun',
    'moodTracker.activities.plan': 'Plan',
    
    // Journal
    'journal.title': 'Personal Journal',
    'journal.subtitle': 'A safe space to express your thoughts and track your emotional journey',
    'journal.recentEntries': 'Recent Entries',
    'journal.totalEntries': 'total entries',
    'journal.noEntries': 'No entries yet',
    'journal.noEntriesDescription': 'Start writing your first journal entry to begin tracking your thoughts and emotions',
    'journal.writeFirst': 'Write Your First Entry',
    'journal.calendar': 'Entry Calendar',
    'journal.calendarDescription': 'View entries by date',
    'journal.entriesFor': 'Entries for',
    'journal.tips.title': 'Journaling Tips',
    'journal.tips.regular': 'Write regularly, even if just a few sentences',
    'journal.tips.honest': 'Be honest with yourself - this is your private space',
    'journal.tips.growth': 'Track patterns in your mood and thoughts over time',
    'journal.tips.grammar': "Don't worry about perfect grammar or spelling",
    'journal.tips.private': 'Your entries are stored locally and remain private',
    'journal.editor.title': 'Write New Entry',
    'journal.editor.editTitle': 'Edit Entry',
    'journal.editor.moodLabel': 'How are you feeling today?',
    'journal.editor.placeholder': 'Write your thoughts here...',
    'journal.editor.tagsLabel': 'Tags (optional)',
    'journal.editor.tagsPlaceholder': 'Add tags separated by commas',
    'journal.editor.save': 'Save Entry',
    'journal.editor.cancel': 'Cancel Edit',
    'journal.entry.edit': 'Edit',
    'journal.entry.delete': 'Delete',
    'journal.stats.title': 'Journal Insights',
    'journal.stats.totalEntries': 'Total Entries',
    'journal.stats.currentStreak': 'Current Streak',
    'journal.stats.longestStreak': 'Longest Streak',
    'journal.stats.mostCommonMood': 'Most Common Mood',
    'journal.stats.days': 'days',
    'journal.stats.moodTrend': 'Mood Trend',
    'journal.stats.improving': 'Improving',
    'journal.stats.stable': 'Stable',
    'journal.stats.declining': 'Declining',
    'journal.summary.today': "Today's Summary",
    'journal.summary.entries': "You've made {count} journal {entries} today.",
    'journal.summary.entry': 'entry',
    'journal.summary.entriesPlural': 'entries',
    'journal.summary.noEntries': 'No entries for today yet. Start your first entry!',
    'journal.progress.weekly': 'Weekly Progress',
    'journal.progress.entriesWeek': '{count} entries this week',
    'journal.progress.goal': 'Goal: 7 entries/week',
    'journal.progress.complete': '{percent}% complete',
    'journal.insights.mood': 'Mood Insights',
    'journal.insights.mostCommon': 'Most common mood:',
    'journal.streak.title': 'Journaling Streak',
    'journal.streak.day': 'day',
    'journal.streak.days': 'days',
    'journal.streak.inRow': 'in a row',
    'journal.streak.keepUp': '🔥 Keep it up! Consistency is key to mental wellness.',
    'common.add': 'Add',
    'journal.toast.errorLoading': 'Error loading entries',
    'journal.toast.errorLoadingDesc': 'There was a problem loading your journal entries.',
    'journal.toast.errorSaving': 'Error saving entries',
    'journal.toast.errorSavingDesc': 'There was a problem saving your journal entries.',
    'journal.toast.entryUpdated': 'Entry updated',
    'journal.toast.entryUpdatedDesc': 'Your journal entry has been successfully updated.',
    'journal.toast.entrySaved': 'Entry saved',
    'journal.toast.entrySavedDesc': 'Your journal entry has been successfully saved.',
    'journal.toast.entryDeleted': 'Entry deleted',
    'journal.toast.entryDeletedDesc': 'Your journal entry has been removed.',
    
    // Rating Popup
    'rating.title': 'Rate Our Website',
    'rating.outOf': 'out of',
    'rating.thankYou': 'Thank You!',
    'rating.feedbackReceived': 'Your feedback has been received.',
    'rating.submit': 'Submit Rating & Sign Out',
    'rating.skip': 'Skip Rating',
    'rating.instructions': 'Click on the stars to rate your experience (1 to 5)'
  },
  hindi: {
    // Navigation
    'nav.home': 'होम',
    'nav.mood': 'मूड ट्रैकर',
    'nav.ai': 'AI सहायता',
    'nav.booking': 'सेशन बुक करें',
    // 'nav.resources' removed (merged into activities)
    'nav.community': 'समुदाय',
    'nav.pomodoro': 'पोमोडोरो',
    'nav.journal': 'जर्नल',
    'nav.activities': 'संसाधन और गतिविधियां',
    'nav.local': 'स्थानीय सहायता',
    'nav.assessment': 'आकलन',
    'nav.admin': 'प्रशासन डैशबोर्ड',
    'nav.donation': 'दान',
    'nav.about': 'हमारे बारे में',
    'nav.profile': 'मेरी प्रोफ़ाइल',
    'nav.signin': 'साइन इन',
    
    // Common
    'common.english': 'English',
    'common.hindi': 'हिंदी',
    'common.navigation': 'नेविगेशन',
    'common.subscribe': 'सब्सक्राइब करें',
    'common.email.placeholder': 'अपना ईमेल दर्ज करें',
    'common.unsubscribe': 'कभी भी अनसब्सक्राइब करें',
    'common.wellness.tips': 'वेलनेस टिप्स और प्लेटफॉर्म अपडेट प्राप्त करें',
    'common.search': 'खोजें',
    'common.clear': 'साफ़ करें',
    'common.start': 'शुरू करें',
    'common.continue': 'जारी रखें',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.submit': 'जमा करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    
    // Footer
    'footer.brand': 'Maitri',
    'footer.brand.tagline': 'तकनीक, समुदाय और दयालु देखभाल के माध्यम से मानसिक कल्याण को सशक्त बनाना। बेहतर मानसिक स्वास्थ्य की आपकी यात्रा यहीं से शुरू होती है।',
    'footer.newsletter.title': 'अपडेटेड रहें',
    'footer.platform': 'प्लेटफॉर्म',
    'footer.support': 'सहायता',
    'footer.legal': 'कानूनी',
    'footer.contact': 'संपर्क',
    'footer.crisis.support': 'संकट सहायता',
    'footer.crisis.text': 'यदि आपके मन में आत्म-हानि के विचार आ रहे हैं, तो हमारी संकट हेल्पलाइन पर कॉल करें: 1800-599-0019',
    'footer.copyright': '© 2025 Maitri. सभी अधिकार सुरक्षित। | अंतरिक्ष यात्री मानसिक स्वास्थ्य के लिए ❤️ से बनाया गया',
    
    // Footer Links
    'footer.link.about': 'हमारे बारे में',
    'footer.link.resources': 'संसाधन',
    'footer.link.community': 'समुदाय',
    'footer.link.ai': 'AI सहायता',
    'footer.link.crisis': 'संकट हेल्पलाइन',
    'footer.link.booking': 'सेशन बुक करें',
    'footer.link.local': 'स्थानीय सहायता',
    'footer.link.emergency': 'आपातकालीन संसाधन',
    'footer.link.privacy': 'गोपनीयता नीति',
    'footer.link.terms': 'सेवा की शर्तें',
    'footer.link.cookies': 'कुकी नीति',
    'footer.link.accessibility': 'पहुंच',
    
    // Contact Info
    'contact.email': 'hello@maitri.space',
    'contact.phone': '1800-599-0019',
    'contact.location': 'मुंबई, भारत',
    
    // Dashboard/Homepage
    'dashboard.hero.title': 'आपका मानसिक स्वास्थ्य सबसे महत्वपूर्ण है',
    'dashboard.hero.subtitle': 'अंतरिक्ष यात्रियों और अंतरिक्ष अन्वेषकों के लिए डिज़ाइन किया गया एक व्यापक डिजिटल मानसिक स्वास्थ्य प्लेटफॉर्म। मिशन-केंद्रित, गोपनीयता-प्रथम, और हमेशा सुलभ—भले ही पृथ्वी के साथ संचार असंभव हो।',
    'dashboard.hero.cta': 'अपनी कल्याण यात्रा शुरू करें',
    'dashboard.hero.emergency': 'आपातकालीन सहायता',
    'dashboard.daily.inspiration': 'दैनिक प्रेरणा',
    'dashboard.daily.subtitle': 'आपकी यात्रा के लिए शक्ति और बुद्धि',
    'dashboard.challenges.title': 'आम चुनौतियां जिन्हें हम संबोधित करते हैं',
    'dashboard.challenges.subtitle': 'सामान्य मानसिक स्वास्थ्य चुनौतियों से निपटने वाले छात्रों के लिए सहायता',
    'dashboard.differentiators.title': 'Maitri क्यों अलग है',
    'dashboard.differentiators.subtitle': 'अंतरिक्ष यात्रियों और अंतरिक्ष अन्वेषकों के लिए विशेष रूप से बनाया गया, अनूठी सुविधाओं के साथ जो लंबी अवधि के अंतरिक्ष मिशनों की वास्तविक चुनौतियों का समाधान करती हैं',
    'dashboard.features.title': 'व्यापक मानसिक स्वास्थ्य सहायता',
    'dashboard.features.subtitle': 'मानसिक कल्याण के लिए आपको जो कुछ भी चाहिए, AI सहायता से लेकर साथियों के संपर्क तक',
    'dashboard.cta.title': 'अपने मानसिक स्वास्थ्य को प्राथमिकता देने के लिए तैयार हैं?',
    'dashboard.cta.subtitle': 'हजारों अंतरिक्ष यात्रियों से जुड़ें जो Maitri के साथ अपने मानसिक कल्याण को नियंत्रित कर रहे हैं',
    'dashboard.cta.get_started': 'आज ही शुरू करें',
    'dashboard.cta.learn_more': 'और जानें',
    
    // Features
    'feature.ai.title': 'TARS AI मानसिक स्वास्थ्य सहायता',
    'feature.ai.description': '24/7 TARS AI साथी जो तुरंत सहारा रणनीतियां, संकट हस्तक्षेप और मनोवैज्ञानिक समर्थन प्रदान करता है—भले ही पृथ्वी के साथ संचार असंभव हो।',
    'feature.ai.action': 'चैट शुरू करें',
    'feature.mood.title': 'मिशन मूड ट्रैकिंग और एनालिटिक्स',
    'feature.mood.description': 'अंतरिक्ष मिशनों के दौरान बेहतर मनोवैज्ञानिक भलाई जागरूकता के लिए साप्ताहिक अंतर्दृष्टि और मिशन-केंद्रित एनालिटिक्स के साथ निजी मूड निगरानी।',
    'feature.mood.action': 'मूड ट्रैक करें',
    'feature.counselling.title': 'मनोवैज्ञानिक समर्थन सत्र',
    'feature.counselling.description': 'अंतरिक्ष यात्रियों के लिए पूर्ण गोपनीयता सुरक्षा के साथ अंतरिक्ष मनोविज्ञान पेशेवरों और मानसिक स्वास्थ्य विशेषज्ञों के लिए सुरक्षित बुकिंग सिस्टम।',
    'feature.counselling.action': 'सेशन बुक करें',
    'feature.resources.title': 'मिशन कल्याण संसाधन हब',
    'feature.resources.description': 'अंतरिक्ष मिशनों के लिए क्यूरेटेड मानसिक स्वास्थ्य सामग्री जिसमें ध्यान गाइड, माइक्रोग्रैविटी के लिए विश्राम ऑडियो, और मिशन-केंद्रित शैक्षिक सामग्री शामिल है।',
    'feature.resources.action': 'संसाधन देखें',
    'feature.community.title': 'अंतरिक्ष यात्री समर्थन समुदाय',
    'feature.community.description': 'अनुभवी अंतरिक्ष अन्वेषकों के साथ मॉडरेटेड अंतरिक्ष यात्री-से-अंतरिक्ष यात्री समर्थन मंच जो मिशन चुनौतियों के लिए सुरक्षित, निर्णय-मुक्त मार्गदर्शन प्रदान करते हैं।',
    'feature.community.action': 'समुदाय में शामिल हों',
    'feature.pomodoro.title': 'मिशन फोकस कोच',
    'feature.pomodoro.description': 'संतुलित अंतरिक्ष संचालन और मनोवैज्ञानिक भलाई के लिए माइंडफुलनेस ब्रेक, कल्याण स्ट्रीक और उत्पादकता अंतर्दृष्टि के साथ एकीकृत मिशन कार्य टाइमर।',
    'feature.pomodoro.action': 'सेशन शुरू करें',
    
    // AI Chat
    'ai.title': 'Maitri AI साथी',
    'ai.subtitle': '24/7 मिशन सहायता • TARS AI • अंतरिक्ष यात्री-केंद्रित',
    'ai.emergency.title': 'संकट में हैं? तुरंत सहायता प्राप्त करें:',
    'ai.emergency.text': 'परिसर आपातकाल: 1800-599-0019 | KIRAN: 1800-599-0019 | आत्महत्या रोकथाम: 9152987821',
    'ai.emergency.call': 'अभी कॉल करें',
    'ai.mode.quick': 'त्वरित',
    'ai.mode.detailed': 'विस्तृत',
    'ai.placeholder': 'अपना संदेश टाइप करें...',
    'ai.send': 'भेजें',
    'ai.welcome': 'नमस्ते! मैं TARS हूं, Maitri से आपका AI साथी। मैं लंबी अवधि के अंतरिक्ष मिशनों के दौरान अंतरिक्ष यात्रियों की अनूठी चुनौतियों को समझता हूं - अलगाव से लेकर मिशन तनाव तक। मैं मिशन-केंद्रित समर्थन, सहारा रणनीतियां और मार्गदर्शन प्रदान करने के लिए 24/7 यहां हूं। आज आप कैसा महसूस कर रहे हैं?',
    
    // Activities
    'activities.title': 'संसाधन और गतिविधियां',
    'activities.description': 'अंतरिक्ष मिशनों के दौरान अंतरिक्ष यात्री मानसिक स्वास्थ्य के लिए क्यूरेटेड वीडियो, ऑडियो, लेख और गाइड, साथ ही लंबी अवधि के मिशनों के दौरान रोज़ अभ्यास करने के लिए इंटरैक्टिव गतिविधियां।',
    'activities.available': 'उपलब्ध गतिविधियां',
    'activities.available.desc': 'विविध कल्याण विकल्प',
    'activities.completed': 'आज पूर्ण किया',
    'activities.completed.desc': 'आदतें बनाते रहें',
    'activities.categories': 'गतिविधि श्रेणियां',
    'activities.categories.desc': 'विभिन्न कल्याण क्षेत्र',
    'activities.streak': 'साप्ताहिक स्ट्रीक',
    'activities.streak.desc': 'गतिविधियों के साथ दिन',
    'activities.recommendations': 'त्वरित सिफारिशें',
    'activities.recommendations.desc': 'अंतरिक्ष मिशनों के दौरान आम अंतरिक्ष यात्री आवश्यकताओं के आधार पर, यहां अभी आजमाने के लिए कुछ लोकप्रिय गतिविधियां हैं:',
    'activities.search.placeholder': 'नाम, लाभ या श्रेणी द्वारा गतिविधियां खोजें...',
    'activities.no.found': 'कोई गतिविधि नहीं मिली',
    'activities.no.found.desc': 'अपने खोज मानदंडों को समायोजित करने या अपनी रुचियों से मेल खाने वाली गतिविधियों को खोजने के लिए विभिन्न श्रेणियों का अन्वेषण करने का प्रयास करें।',
    'activities.clear.filters': 'फिल्टर साफ़ करें',
    'activities.find.activity': 'गतिविधि खोजें',
    'activities.tips.title': 'गतिविधि टिप्स',
    'activities.time.suggestions': 'समय-आधारित सुझाव',
    
    // Resources (page removed)
    'resources.title': 'संसाधन',
    'resources.description': 'क्यूरेटेड मानसिक स्वास्थ्य सामग्री।',
    'resources.search.placeholder': 'खोजें...',
    'resources.category.all': 'सभी संसाधन',
    'resources.category.articles': 'लेख और गाइड',
    'resources.category.meditation': 'ध्यान और ऑडियो',
    'resources.category.crisis': 'संकट सहायता',
    'resources.category.tools': 'स्व-सहायता उपकरण',
    'resources.category.videos': 'शैक्षणिक वीडियो',
    'resources.no.found': 'कोई संसाधन नहीं मिला',
    'resources.no.found.desc': 'अपने खोज मानदंडों को समायोजित करने या विभिन्न श्रेणियों को ब्राउज़ करने का प्रयास करें।',
    
    // Floating Action Button
    'fab.ai.chat': 'AI चैट सहायता',
    'fab.emergency': 'आपातकालीन हेल्पलाइन',
    'fab.help': 'सहायता प्राप्त करें',
    
    // Mood Tracker
    'moodTracker.title': 'मूड ट्रैकर',
    'moodTracker.subtitle': 'अपनी भावनात्मक भलाई को ट्रैक करें और पैटर्न खोजें',
    'moodTracker.dailyEntry': 'आज का मूड',
    'moodTracker.dailyDescription': 'आज आप कैसा महसूस कर रहे हैं?',
    'moodTracker.moods.great': 'बहुत अच्छा',
    'moodTracker.moods.good': 'अच्छा',
    'moodTracker.moods.okay': 'ठीक',
    'moodTracker.moods.low': 'कम',
    'moodTracker.moods.struggling': 'संघर्ष',
    'moodTracker.whatsOnMind': 'आपके मन में क्या है? (वैकल्पिक)',
    'moodTracker.placeholder': 'अपने विचार, भावनाएं या आज क्या हुआ साझा करें...',
    'moodTracker.recordMood': 'मूड रिकॉर्ड करें',
    'moodTracker.recorded': 'मूड रिकॉर्ड हो गया ✓',
    'moodTracker.weekOverview': 'साप्ताहिक अवलोकन',
    'moodTracker.weekDescription': 'पिछले सप्ताह में आपका मूड पैटर्न',
    'moodTracker.averageMood': 'औसत मूड',
    'moodTracker.progress': 'आपकी प्रगति',
    'moodTracker.daysTracked': 'ट्रैक किए गए दिन',
    'moodTracker.wellnessStreak': 'कल्याण स्ट्रीक',
    'moodTracker.aboveAverage': 'औसत से ऊपर',
    'moodTracker.insights': 'मूड अंतर्दृष्टि',
    'moodTracker.patternDetected': 'पैटर्न का पता चला',
    'moodTracker.patternMessage': 'आपका मूड सप्ताहांत में सुधरने की प्रवृत्ति रखता है। सप्ताह के दिनों में अधिक आरामदायक गतिविधियों को शामिल करने पर विचार करें।',
    'moodTracker.positiveTrigger': 'सकारात्मक ट्रिगर',
    'moodTracker.triggerMessage': 'व्यायाम और ध्यान आपके मूड को काफी बढ़ाते दिखाई देते हैं।',
    'moodTracker.viewResources': 'संसाधन देखें',
    'moodTracker.privacyNotice': 'आपका मूड डेटा निजी और सुरक्षित है। केवल आप अपनी व्यक्तिगत प्रविष्टियां देख सकते हैं।',
    'moodTracker.days.mon': 'सोम',
    'moodTracker.days.tue': 'मंगल',
    'moodTracker.days.wed': 'बुध',
    'moodTracker.days.thu': 'गुरु',
    'moodTracker.days.fri': 'शुक्र',
    'moodTracker.days.sat': 'शनि',
    'moodTracker.days.sun': 'रवि',
    'moodTracker.activities.study': 'अध्ययन',
    'moodTracker.activities.exercise': 'व्यायाम',
    'moodTracker.activities.social': 'सामाजिक',
    'moodTracker.activities.rest': 'आराम',
    'moodTracker.activities.meditation': 'ध्यान',
    'moodTracker.activities.exam': 'परीक्षा',
    'moodTracker.activities.stress': 'तनाव',
    'moodTracker.activities.friends': 'मित्र',
    'moodTracker.activities.relax': 'विश्राम',
    'moodTracker.activities.family': 'परिवार',
    'moodTracker.activities.fun': 'मनोरंजन',
    'moodTracker.activities.plan': 'योजना',
    
    // Journal
    'journal.title': 'व्यक्तिगत जर्नल',
    'journal.subtitle': 'अपने विचारों को व्यक्त करने और अपनी भावनात्मक यात्रा को ट्रैक करने के लिए एक सुरक्षित स्थान',
    'journal.recentEntries': 'हाल की प्रविष्टियां',
    'journal.totalEntries': 'कुल प्रविष्टियां',
    'journal.noEntries': 'अभी तक कोई प्रविष्टि नहीं',
    'journal.noEntriesDescription': 'अपने विचारों और भावनाओं को ट्रैक करना शुरू करने के लिए अपनी पहली जर्नल प्रविष्टि लिखना शुरू करें',
    'journal.writeFirst': 'अपनी पहली प्रविष्टि लिखें',
    'journal.calendar': 'प्रविष्टि कैलेंडर',
    'journal.calendarDescription': 'तारीख के अनुसार प्रविष्टियां देखें',
    'journal.entriesFor': 'प्रविष्टियां',
    'journal.tips.title': 'जर्नलिंग टिप्स',
    'journal.tips.regular': 'नियमित रूप से लिखें, भले ही केवल कुछ वाक्य हों',
    'journal.tips.honest': 'अपने साथ ईमानदार रहें - यह आपका निजी स्थान है',
    'journal.tips.growth': 'समय के साथ अपने मूड और विचारों में पैटर्न ट्रैक करें',
    'journal.tips.grammar': 'सही व्याकरण या वर्तनी की चिंता न करें',
    'journal.tips.private': 'आपकी प्रविष्टियां स्थानीय रूप से संग्रहीत हैं और निजी रहती हैं',
    'journal.editor.title': 'नई प्रविष्टि लिखें',
    'journal.editor.editTitle': 'प्रविष्टि संपादित करें',
    'journal.editor.moodLabel': 'आज आप कैसा महसूस कर रहे हैं?',
    'journal.editor.placeholder': 'अपने विचार यहां लिखें...',
    'journal.editor.tagsLabel': 'टैग (वैकल्पिक)',
    'journal.editor.tagsPlaceholder': 'अल्पविराम से अलग करके टैग जोड़ें',
    'journal.editor.save': 'प्रविष्टि सेव करें',
    'journal.editor.cancel': 'संपादन रद्द करें',
    'journal.entry.edit': 'संपादित करें',
    'journal.entry.delete': 'हटाएं',
    'journal.stats.title': 'जर्नल अंतर्दृष्टि',
    'journal.stats.totalEntries': 'कुल प्रविष्टियां',
    'journal.stats.currentStreak': 'वर्तमान स्ट्रीक',
    'journal.stats.longestStreak': 'सबसे लंबी स्ट्रीक',
    'journal.stats.mostCommonMood': 'सबसे आम मूड',
    'journal.stats.days': 'दिन',
    'journal.stats.moodTrend': 'मूड रुझान',
    'journal.stats.improving': 'सुधार',
    'journal.stats.stable': 'स्थिर',
    'journal.stats.declining': 'गिरावट',
    'journal.summary.today': 'आज का सारांश',
    'journal.summary.entries': 'आपने आज {count} जर्नल {entries} बनाई हैं।',
    'journal.summary.entry': 'प्रविष्टि',
    'journal.summary.entriesPlural': 'प्रविष्टियां',
    'journal.summary.noEntries': 'आज के लिए अभी तक कोई प्रविष्टि नहीं। अपनी पहली प्रविष्टि शुरू करें!',
    'journal.progress.weekly': 'साप्ताहिक प्रगति',
    'journal.progress.entriesWeek': 'इस सप्ताह {count} प्रविष्टियां',
    'journal.progress.goal': 'लक्ष्य: 7 प्रविष्टियां/सप्ताह',
    'journal.progress.complete': '{percent}% पूर्ण',
    'journal.insights.mood': 'मूड अंतर्दृष्टि',
    'journal.insights.mostCommon': 'सबसे आम मूड:',
    'journal.streak.title': 'जर्नलिंग स्ट्रीक',
    'journal.streak.day': 'दिन',
    'journal.streak.days': 'दिन',
    'journal.streak.inRow': 'लगातार',
    'journal.streak.keepUp': '🔥 इसे बनाए रखें! निरंतरता मानसिक कल्याण की कुंजी है।',
    'common.add': 'जोड़ें',
    'journal.toast.errorLoading': 'प्रविष्टियां लोड करने में त्रुटि',
    'journal.toast.errorLoadingDesc': 'आपकी जर्नल प्रविष्टियों को लोड करने में समस्या हुई।',
    'journal.toast.errorSaving': 'प्रविष्टियां सेव करने में त्रुटि',
    'journal.toast.errorSavingDesc': 'आपकी जर्नल प्रविष्टियों को सेव करने में समस्या हुई।',
    'journal.toast.entryUpdated': 'प्रविष्टि अपडेट हुई',
    'journal.toast.entryUpdatedDesc': 'आपकी जर्नल प्रविष्टि सफलतापूर्वक अपडेट हो गई है।',
    'journal.toast.entrySaved': 'प्रविष्टि सेव हुई',
    'journal.toast.entrySavedDesc': 'आपकी जर्नल प्रविष्टि सफलतापूर्वक सेव हो गई है।',
    'journal.toast.entryDeleted': 'प्रविष्टि हटाई गई',
    'journal.toast.entryDeletedDesc': 'आपकी जर्नल प्रविष्टि हटा दी गई है।',
    
    // Rating Popup
    'rating.title': 'हमारी वेबसाइट को रेट करें',
    'rating.outOf': 'में से',
    'rating.thankYou': 'धन्यवाद!',
    'rating.feedbackReceived': 'आपकी प्रतिक्रिया प्राप्त हो गई है।',
    'rating.submit': 'रेटिंग जमा करें और साइन आउट करें',
    'rating.skip': 'रेटिंग छोड़ें',
    'rating.instructions': 'अपने अनुभव को रेट करने के लिए सितारों पर क्लिक करें (1 से 5)'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('english');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['english']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}